#pragma once

// Umbrella header — pulls in the public Argus surface in one include.

#include "ad.hpp"
#include "atmosphere.hpp"
#include "lensing.hpp"
#include "chain_io.hpp"
#include "diagnostics.hpp"
#include "dual.hpp"
#include "geometry.hpp"
#include "hitran.hpp"
#include "interferometry.hpp"
#include "ir.hpp"
#include "jwst_data.hpp"
#include "line_list.hpp"
#include "mcmc.hpp"
#include "nn.hpp"
#include "opacity.hpp"
#include "partition.hpp"
#include "radiative_transfer.hpp"
#include "retrieval.hpp"
#include "tensor.hpp"
#include "version.hpp"
#include "voigt.hpp"
